force-app/main/staging/objects/Staging_Field__c/Staging_Field__c.object-meta.xml
<CustomObject>
    <description>This is where the details of a staging record will be held, it will contain the field from the source and the field that it has been mapped to in Salesforce.

TODO Could include fields that are all data types so that all field values are parsed upfront</description>
    <label>Staging Field</label>
    <nameField>
        <displayFormat>SF-{0000000}</displayFormat>
        <label>Staging Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Field__c/fields/Boolean_Value__c.field-meta.xml
<CustomField>
    <fullName>Boolean_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field that will store the boolean field value</description>
    <label>Boolean Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Datetime_Value__c.field-meta.xml
<CustomField>
    <fullName>Datetime_Value__c</fullName>
    <description>This field will store the date or date time target field values</description>
    <label>Datetime Value</label>
    <type>DateTime</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Number_Value__c.field-meta.xml
<CustomField>
    <fullName>Number_Value__c</fullName>
    <description>The value field that will store number types, eg percentage, currency or numbers</description>
    <label>Number Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Salesforce_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Name__c</fullName>
    <description>The API name for the field in Salesforce that this record should be migrated to</description>
    <label>Salesforce Field Name</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <formula>Staging_Header__r.Salesforce_Object__c</formula>
    <label>Salesforce Object</label>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Staging_Header__c.field-meta.xml
<CustomField>
    <fullName>Staging_Header__c</fullName>
    <label>Staging Header</label>
    <referenceTo>Staging_Header__c</referenceTo>
    <relationshipLabel>Staging Fields</relationshipLabel>
    <relationshipName>Staging_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/String_Value__c.field-meta.xml
<CustomField>
    <fullName>String_Value__c</fullName>
    <description>String version of the value field</description>
    <label>String Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Time_Value__c.field-meta.xml
<CustomField>
    <fullName>Time_Value__c</fullName>
    <description>The field that will hold a time type field</description>
    <label>Time Value</label>
    <type>Time</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>The unique id for the staging record, this will be a concatenation of the parents unique id and the field that is input, meaning that fields should be unique in every request</description>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Header__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <description>The object API name that the target record should be moved to</description>
    <label>Salesforce Object</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>This will hold the unique id for the staging record, this will be a concatenation of the source object name, the change date and the source unique id</description>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/staging/api/classes/StagingFieldBuilder.cls
/**
 * Created by admin-1019 on 09/11/2018.
 */

public class StagingFieldBuilder {

    private final Staging_Field__c stagingFieldToBuild = new Staging_Field__c();
    private static final Map<DisplayType, SObjectField> displayTypesToTargetFields = new Map<DisplayType, SObjectField>{
        DisplayType.ANYTYPE => Staging_Field__c.String_Value__c,
        DisplayType.BASE64 => Staging_Field__c.String_Value__c,
        DisplayType.BOOLEAN => Staging_Field__c.Boolean_Value__c,
        DisplayType.COMPLEXVALUE => Staging_Field__c.String_Value__c,
        DisplayType.CURRENCY => Staging_Field__c.Number_Value__c,
        DisplayType.DATE => Staging_Field__c.Datetime_Value__c,
        DisplayType.DATETIME => Staging_Field__c.Datetime_Value__c,
        DisplayType.DOUBLE => Staging_Field__c.Number_Value__c,
        DisplayType.EMAIL => Staging_Field__c.String_Value__c,
        DisplayType.ENCRYPTEDSTRING => Staging_Field__c.String_Value__c,
        DisplayType.ID => Staging_Field__c.String_Value__c,
        DisplayType.INTEGER => Staging_Field__c.Number_Value__c,
        DisplayType.JSON => Staging_Field__c.String_Value__c,
        DisplayType.LONG => Staging_Field__c.Number_Value__c,
        DisplayType.MULTIPICKLIST => Staging_Field__c.String_Value__c,
        DisplayType.PERCENT => Staging_Field__c.Number_Value__c,
        DisplayType.PHONE => Staging_Field__c.String_Value__c,
        DisplayType.PICKLIST => Staging_Field__c.String_Value__c,
        DisplayType.REFERENCE => Staging_Field__c.String_Value__c,
        DisplayType.STRING => Staging_Field__c.String_Value__c,
        DisplayType.TEXTAREA => Staging_Field__c.String_Value__c,
        DisplayType.TIME => Staging_Field__c.Time_Value__c,
        DisplayType.URL => Staging_Field__c.String_Value__c
    };

    public void setParent(Staging_Header__c parentHeader) {
        stagingFieldToBuild.Staging_Header__c = parentHeader.Id;
        stagingFieldToBuild.Staging_Header__r = parentHeader;
    }

    private String getSObjectName() {
        return stagingFieldToBuild.Staging_Header__r.Salesforce_Object__c
    }

    public void setField(String fieldName, Object fieldValue) {
        DisplayType targetFieldType = SchemaFacade.getInstance().getFieldDescribe(getSObjectName(), fieldName).getType();
        stagingFieldToBuild.put(displayTypesToTargetFields.get(targetFieldType), fieldValue);
    }

    public Staging_Field__c build() {
        validateStagingField();
        stagingFieldToBuild.Unique_Id__c = getUniqueId();
        return stagingFieldToBuild;
    }

    private void validateStagingField() {
        if (isNotValid()) {
//                throw new StagingException
        }
    }

    private Boolean isNotValid() {
        return String.isBlank(stagingFieldToBuild.Staging_Header__r.Unique_Id__c) ||
            String.isBlank(stagingFieldToBuild.Salesforce_Field_Name__c);
    }

    private String getUniqueId() {
        return stagingFieldToBuild.Staging_Header__r.Unique_Id__c + stagingFieldToBuild.Salesforce_Field_Name__c;
    }
}