force-app/main/staging/objects/Staging_Field__c/Staging_Field__c.object-meta.xml
<CustomObject>
    <description>This is where the details of a staging record will be held, it will contain the field from the source and the field that it has been mapped to in Salesforce.

TODO Could include fields that are all data types so that all field values are parsed upfront</description>
    <label>Staging Field</label>
    <nameField>
        <displayFormat>SF-{0000000}</displayFormat>
        <label>Staging Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Field__c/fields/Salesforce_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Name__c</fullName>
    <description>The API name for the field in Salesforce that this record should be migrated to</description>
    <label>Salesforce Field Name</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <formula>Staging_Header__r.Salesforce_Object__c</formula>
    <label>Salesforce Object</label>
    <type>Text</type>
</CustomField>

force-app/main/staging/validation/classes/StagingFieldValidator.cls
/**
 * Created by admin-1019 on 10/11/2018.
 */

public class StagingFieldValidator implements Triggerable {

    private final StagingValidator validator = new StagingValidator();

    public void register(SObjectTriggerWrapper wrappedSObject) {
        Staging_Field__c stagingField = (Staging_Field__c) wrappedSObject.getSObject();
        if (validator.isNotValidField(stagingField)) {
            stagingField.addError('The field "' + stagingField.Salesforce_Object__c + '" does not exist for the object "' + stagingField.Salesforce_Field_Name__c + '"');
        }
    }

    public void performAction() {
        // do nothing as validation has occurred already
    }
}