force-app/main/staging/objects/Staging_Field__c/Staging_Field__c.object-meta.xml
<CustomObject>
    <description>This is where the details of a staging record will be held, it will contain the field from the source and the field that it has been mapped to in Salesforce.

TODO Could include fields that are all data types so that all field values are parsed upfront</description>
    <label>Staging Field</label>
    <nameField>
        <displayFormat>SF-{0000000}</displayFormat>
        <label>Staging Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Field__c/fields/Staging_Header__c.field-meta.xml
<CustomField>
    <fullName>Staging_Header__c</fullName>
    <label>Staging Header</label>
    <referenceTo>Staging_Header__c</referenceTo>
    <relationshipLabel>Staging Fields</relationshipLabel>
    <relationshipName>Staging_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/api/classes/StagingBuilder.cls
/**
 * Created by admin-1019 on 09/11/2018.
 */

global class StagingBuilder {

    private Datetime changedDatetime = Datetime.now();
    private String salesforceObject;
    private String sourceIdentifier;
    private Map<String, Object> fieldValues = new Map<String, Object>();
    private StagingHeaderBuilder header = new StagingHeaderBuilder();
    private Staging_Header__c headerRecord = new Staging_Header__c();
    private List<Staging_Field__c> fields = new List<Staging_Field__c>();

    global void setTargetObject(String salesforceObject) {
        this.salesforceObject = salesforceObject;
    }

    global void setSourceId(String sourceId) {
        this.sourceIdentifier = sourceId;
    }

    global void setField(String fieldName, Object fieldValue) {
        fieldValues.put(fieldName, fieldValue);
    }

    global void setStagingSObject(SObject sObjectToStage) {
        setTargetObject(String.valueOf(sObjectToStage.getSObjectType()));
        Map<String, Object> sObjectFieldValues = sObjectToStage.getPopulatedFieldsAsMap();
        fieldValues.putAll(sObjectFieldValues);
    }

    public Staging_Header__c getHeader() {
        if (header == null || header.isNotValid()) {
            header = new StagingHeaderBuilder();
            buildHeader();
        }
        return headerRecord;
    }

    private void buildHeader() {
        header.setChangedDatetime(changedDatetime);
        header.setSourceIdentifier(sourceIdentifier);
        header.setSalesforceObject(salesforceObject);
        headerRecord = header.build();
    }

    public List<Staging_Field__c> getFields() {
        if (fields == null || fields.isEmpty()) {
            fields = new List<Staging_Field__c>();
            buildFields();
        }
        return fields;
    }

    private void buildFields() {
        for (String fieldName : fieldValues.keySet()) {
            StagingFieldBuilder stagingField = new StagingFieldBuilder();
            stagingField.setField(fieldName, fieldValues.get(fieldName));
            stagingField.setParent(getHeader());
            fields.add(stagingField.build());
        }
    }
}