force-app/main/staging/objects/Staging_Field__c/Staging_Field__c.object-meta.xml
<CustomObject>
    <description>This is where the details of a staging record will be held, it will contain the field from the source and the field that it has been mapped to in Salesforce.

TODO Could include fields that are all data types so that all field values are parsed upfront</description>
    <label>Staging Field</label>
    <nameField>
        <displayFormat>SF-{0000000}</displayFormat>
        <label>Staging Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Field__c/fields/Staging_Header__c.field-meta.xml
<CustomField>
    <fullName>Staging_Header__c</fullName>
    <label>Staging Header</label>
    <referenceTo>Staging_Header__c</referenceTo>
    <relationshipLabel>Staging Fields</relationshipLabel>
    <relationshipName>Staging_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>The unique id for the staging record, this will be a concatenation of the parents unique id and the field that is input, meaning that fields should be unique in every request</description>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This will track the import of the staging record,</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Import In Progress</fullName>
            </value>
            <value>
                <fullName>Import Completed</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>This will hold the unique id for the staging record, this will be a concatenation of the source object name, the change date and the source unique id</description>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/staging/api/classes/StagingCreatorBulk.cls
/**
 * Created by admin-1019 on 09/11/2018.
 */
@RestResource(UrlMapping='/bulkstaging')
global class StagingCreatorBulk {


    /*
    Example callout
{
    "stagingDetails": [
        {
            "changedDatetime": "2011-01-10T00:00:00.000Z",
            "sourceIdentifier": "UUID1",
            "salesforceObject": "value for string2",
            "fieldValues": {
                "firstName": "Gavin",
                "lastName": "Palmer",
                "age": 25
            }
        },
        {
            "changedDatetime": "2012-01-10T00:00:00.000Z",
            "sourceIdentifier": "UUID12",
            "salesforceObject": "value for string2",
            "fieldValues": {
                "firstName": "Fred",
                "lastName": "Flintof",
                "age": 29
            }
        }
    ]
}
     */


    @HttpPost
    global static List<StagingResponse> insertStaging() {
        String jsonBody = RestContext.request.requestBody.toString();
        List<StagingBuilder> stagingDetails = (List<StagingBuilder>) JSON.deserialize(jsonBody, List<StagingBuilder>.class);
        Map<String, StagingResponse> responsesByStagingId = new Map<String, StagingResponse>();
        List<Staging_Header__c> orderedHeaders = new List<Staging_Header__c>();
        Map<String, List<Staging_Field__c>> stagingFieldsByHeaderId = new Map<String, List<Staging_Field__c>>();
        for (StagingBuilder stagingDetail : stagingDetails) {
            Staging_Header__c header = stagingDetail.getHeader();
            header.Status__c = 'Import In Progress';
            orderedHeaders.add(header);
            List<Staging_Field__c> stagingFields = stagingDetail.getFields();
            stagingFieldsByHeaderId.put(header.Unique_Id__c, stagingFields);
        }
        List<Database.UpsertResult> stagingHeaderUpsertResults = Database.upsert(
            orderedHeaders,
            Staging_Header__c.Unique_Id__c,
            false
        );
        Map<String, Staging_Header__c> stagingHeaderMap = new Map<String, Staging_Header__c>();
        for (Integer i = 0; i < stagingHeaderUpsertResults.size(); i++) {
            Database.UpsertResult stagingResult = stagingHeaderUpsertResults[i];
            Staging_Header__c header = orderedHeaders[i];
            final String headerUniqueId = header.Unique_Id__c;
            StagingResponse response = new StagingResponse(header);
            if (!stagingResult.isSuccess()) {
                response.addErrors(stagingResult.getErrors());
                responsesByStagingId.put(headerUniqueId, response);
                stagingFieldsByHeaderId.remove(headerUniqueId);
            } else {
                stagingHeaderMap.put(headerUniqueId, header);
            }
        }
        List<Staging_Field__c> stagingFieldsToUpsert = new List<Staging_Field__c>();
        for (List<Staging_Field__c> fields : stagingFieldsByHeaderId.values()) {
            stagingFieldsToUpsert.addAll(fields);
        }
        List<Database.UpsertResult> stagingFieldUpsertResults = Database.upsert(
            stagingFieldsToUpsert,
            Staging_Field__c.Unique_Id__c,
            false
        );
        Map<Id, Staging_Header__c> stagingHeadersToUpdateById = new Map<Id, Staging_Header__c>();
        for (Integer i = 0; i < stagingFieldUpsertResults.size(); i++) {
            Database.UpsertResult fieldResult = stagingFieldUpsertResults[i];
            Staging_Field__c field = stagingFieldsToUpsert[i];
            final String stagingId = field.Staging_Header__r.Unique_Id__c;
            Staging_Header__c header = stagingHeaderMap.get(stagingId);
            if (!fieldResult.isSuccess()) {
                StagingResponse response = responsesByStagingId.get(stagingId);
                response.addErrors(fieldResult.getErrors());
                header.Status__c = 'Failed';
                stagingHeaderMap.remove(stagingId);
            } else {
                header.Status__c = 'Import Completed';
            }
            stagingHeadersToUpdateById.put(header.Id, header);
        }
        List<Staging_Header__c> stagingHeadersToUpdate = stagingHeadersToUpdateById.values();
        List<Database.SaveResult> completedResults = Database.update(stagingHeadersToUpdate, false);
        for (Integer i = 0; i < completedResults.size(); i++) {
            if (!completedResults[i].isSuccess()) {
                final String stagingId = stagingHeadersToUpdate[i].Unique_Id__c;
                StagingResponse response = responsesByStagingId.get(stagingId);
                response.addErrors(completedResults[i].getErrors());
            }
        }
        return responsesByStagingId.values();
    }
}