force-app/main/staging/objects/Staging_Field__c/Staging_Field__c.object-meta.xml
<CustomObject>
    <description>This is where the details of a staging record will be held, it will contain the field from the source and the field that it has been mapped to in Salesforce.

TODO Could include fields that are all data types so that all field values are parsed upfront</description>
    <label>Staging Field</label>
    <nameField>
        <displayFormat>SF-{0000000}</displayFormat>
        <label>Staging Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Field__c/fields/Input_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Input_Field_Value__c</fullName>
    <description>The string value that the field that has come from the external system</description>
    <label>Input Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Salesforce_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Name__c</fullName>
    <description>The API name for the field in Salesforce that this record should be migrated to</description>
    <label>Salesforce Field Name</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <formula>Staging_Header__r.Salesforce_Object__c</formula>
    <label>Salesforce Object</label>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Field__c/fields/Staging_Header__c.field-meta.xml
<CustomField>
    <fullName>Staging_Header__c</fullName>
    <label>Staging Header</label>
    <referenceTo>Staging_Header__c</referenceTo>
    <relationshipLabel>Staging Fields</relationshipLabel>
    <relationshipName>Staging_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Header__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <description>The object API name that the target record should be moved to</description>
    <label>Salesforce Object</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/validation/classes/StagingValidator.cls
/**
 * Created by admin-1019 on 11/11/2018.
 */

public class StagingValidator {

    private final SchemaFacade schema = SchemaFacade.getInstance();

    public Boolean isNotValidHeader(Staging_Header__c stagingHeaderToValidate) {
        return schema.isNotValidSObject(stagingHeaderToValidate.Salesforce_Object__c);
    }

    public Boolean isNotValidField(Staging_Field__c stagingFieldToValidate) {
        final String stagedObjectName = stagingFieldToValidate.Salesforce_Object__c;
        final String stagedFieldName = stagingFieldToValidate.Salesforce_Field_Name__c;
        return schema.isNotValidField(stagedObjectName, stagedFieldName) ||
            isNotCorrectFieldType(stagingFieldToValidate);
    }

    private Boolean isNotCorrectFieldType(Staging_Field__c stagingFieldToValidate) {
        final String stagedObjectName = stagingFieldToValidate.Salesforce_Object__c;
        final String stagedFieldName = stagingFieldToValidate.Salesforce_Field_Name__c;
        DisplayType fieldType = schema.getFieldDescribe(stagedObjectName, stagedFieldName).getType();
        Parsable parser = new DisplayTypeParser(fieldType);
        // TODO see if there is a better way to validate the field type
//        try {
//            parser.parse(stagingFieldToValidate.Input_Field_Value__c);
//        } catch (Exception ex) {
//            return false;
//        }
        return true;
    }
}