force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Header__c/fields/Source_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Unique_Id__c</fullName>
    <description>This is the unique id from the source system, this can aid in any matching that is required with existing Salesforce records</description>
    <externalId>true</externalId>
    <label>Source Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/api/classes/StagingResponse.cls
/**
 * Created by admin-1019 on 09/11/2018.
 */

global class StagingResponse {
    private Boolean success = true;
    private String message;
    private final Id headerId;
    private final String sourceId;

    public StagingResponse(Staging_Header__c header) {
        headerId = header.Id;
        sourceId = header.Source_Unique_Id__c;
    }

    public void addError(String message) {
        setMessage(message);
        success = false;
    }

    public void addErrors(List<Database.Error> errors) {
        StringBuilder errorMessage = new StringBuilder();
        errorMessage.setSeparator('\n');
        for (Database.Error error : errors) {
            errorMessage.append(error.getMessage());
        }
        addError(errorMessage.toString());
    }

    public void setMessage(String message) {
        this.message = message;
    }
}