force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Header__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <description>The object API name that the target record should be moved to</description>
    <label>Salesforce Object</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/validation/classes/StagingHeaderValidator.cls
/**
 * Created by admin-1019 on 10/11/2018.
 */

public class StagingHeaderValidator implements Triggerable {

    private final StagingValidator validator = new StagingValidator();

    public void register(SObjectTriggerWrapper wrappedSObject) {
        Staging_Header__c stagingHeader = (Staging_Header__c) wrappedSObject.getSObject();
        if (validator.isNotValidHeader(stagingHeader)) {
            stagingHeader.addError('Object "' + stagingHeader.Salesforce_Object__c + '" does not exist in the salesforce schema');
        }
    }

    public void performAction() {
        // do nothing as validation has occurred already
    }
}