force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Header__c/fields/Change_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Change_Datetime__c</fullName>
    <description>Date time the change occurred in the external system, this is used to ensure changes that are sent in the api call are only created once in Salesforce</description>
    <label>Change Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <description>The object API name that the target record should be moved to</description>
    <label>Salesforce Object</label>
    <length>83</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/fields/Source_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Unique_Id__c</fullName>
    <description>This is the unique id from the source system, this can aid in any matching that is required with existing Salesforce records</description>
    <externalId>true</externalId>
    <label>Source Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>This will hold the unique id for the staging record, this will be a concatenation of the source object name, the change date and the source unique id</description>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/staging/api/classes/StagingHeaderBuilder.cls
/**
 * Created by admin-1019 on 09/11/2018.
 */

public class StagingHeaderBuilder {
    private final Staging_Header__c stagingHeaderToBuild = new Staging_Header__c();

    public void setChangedDatetime(Datetime changeDatetime) {
        stagingHeaderToBuild.Change_Datetime__c = changeDatetime;
    }

    public void setSalesforceObject(String salesforceObject) {
        stagingHeaderToBuild.Salesforce_Object__c = salesforceObject;
    }

    public void setSourceIdentifier(String sourceIdentifier) {
        stagingHeaderToBuild.Source_Unique_Id__c = sourceIdentifier;
    }

    public Staging_Header__c build() {
        validateStagingRecord();
        stagingHeaderToBuild.Unique_Id__c = getUniqueId();
        return stagingHeaderToBuild;
    }

    private void validateStagingRecord() {
        if (isNotValid()) {
//                throw new StagingException
        }
    }

    public Boolean isNotValid() {
        return String.isBlank(stagingHeaderToBuild.Salesforce_Object__c) ||
            stagingHeaderToBuild.Change_Datetime__c == null ||
            String.isBlank(stagingHeaderToBuild.Source_Unique_Id__c);
    }

    private String getUniqueId() {
        return stagingHeaderToBuild.Salesforce_Object__c + stagingHeaderToBuild.Change_Datetime__c + stagingHeaderToBuild.Source_Unique_Id__c;
    }
}