force-app/main/staging/objects/Staging_Header__c/Staging_Header__c.object-meta.xml
<CustomObject>
    <description>This will be a header for staging an imported Salesforce record that needs some form of validation before it is accepted into Salesforce</description>
    <label>Staging Header</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Staging Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/staging/objects/Staging_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This will track the import of the staging record,</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Import In Progress</fullName>
            </value>
            <value>
                <fullName>Import Completed</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/staging/objects/Staging_Header__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>This will hold the unique id for the staging record, this will be a concatenation of the source object name, the change date and the source unique id</description>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/staging/api/classes/StagingCreator.cls
/**
 * Created by admin-1019 on 09/11/2018.
 */
@RestResource(UrlMapping='/staging')
global class StagingCreator {
    @HttpPost
    global static StagingResponse insertStaging(StagingBuilder stagingDetail) {
        StagingResponse response = new StagingResponse();
        Staging_Header__c stagingHeader = stagingDetail.getHeader();
        stagingHeader.Status__c = 'Import In Progress';
        try {
            upsert stagingHeader Unique_Id__c;

            upsert stagingDetail.getFields() Unique_Id__c;

            stagingHeader.Status__c = 'Import Completed';
            upsert stagingHeader Unique_Id__c;
        } catch (DmlException exceptionToHandle) {
            response.addError(exceptionToHandle.getMessage());
            return response;
        }
        response.setHeaderId(stagingHeader.Id);
        return response;
    }
}